version: '3'
services:
  postgres:
    container_name: airflow_db
    restart: always
    image: postgres:14.10
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts

  redis:
    image: redis:6

  airflow-webserver:
    build: 
      context: .docker/airflow
    container_name: airflow
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./:/opt/airflow/
    env_file:
      - .env
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
        airflow scheduler & airflow webserver
      "

volumes:
  postgres_data:
